upstream task-dashboard-backend {
    server task-dashboard-app-1:8080;
    server task-dashboard-app-2:8080;
}
    server {
        listen 80;
        location / {
            proxy_pass http://task-dashboard-backend;
        }
    }
